[build]
  publish = "."
  command = ""

# Redirect rule for SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Specific redirects for direct file access
[[redirects]]
  from = "/test"
  to = "/test.html"
  status = 200
  force = true

[[redirects]]
  from = "/uperiseindia"
  to = "/uperiseindia.html"
  status = 200
  force = true

# Headers to improve rendering and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"